version: "3.0"
services:
  redis:
    image: redis:7.0.4
    ports:
      - "6379:6379"

  fam100:
    build: .
    command: /fam100 -quorum 3
    depends_on:
      - redis
    volumes:
      - "./qna:/qna"
    environment:
      TELEGRAM_KEY: "5443437398:AAGKj4hns5TPsJp7ArX41HugAz36RWoopFM"
      QUESTION_DB_PATH: "qna/questions.txt"
      REDIS_ADDR: "redis-16118.c257.us-east-1-3.ec2.cloud.redislabs.com:16118"

